apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: app
  newName: mateuslopess/realtime-chat-api
  newTag: c58b625834eb8b45c0d3d3b45ba4cbc288fc5146
- name: mateuslopess/realtime-chat-api
  newTag: 07267d46e8c7856b6f850151e1b3d11b1edd5f58
