apiVersion: v1
kind: Service
metadata:
  name: realtime-chat-api-service
  namespace: backend
spec:
  type: NodePort
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 30001
